"""pending profile photo

Revision ID: 17a843aaeb54
Revises: a7dd0c80c4a4
Create Date: 2026-09-25 00:39:33.224171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a843aaeb54'
down_revision: Union[str, Sequence[str], None] = 'a7dd0c80c4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_photo_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('pending_photo_reason', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_photo_reason')
    op.drop_column('users', 'pending_photo_url')
    # ### end Alembic commands ###
